### ISSUE TITLE
CLA records and automation

### ISSUE THREAD

**Issue by sbesson** [conda/clabot-config#4]
Hi Conda community,

we are in the process of implementing a CLA for the [OME](https://github.com/ome/) organization and have been using your [guidelines](https://conda.io/en/latest/contributing.html#conda-contributor-license-agreement) as a reference for this process. Thanks for making them public in the first place..

I have two questions related to the automation and record keeping. I had looked at https://finos.github.io/cla-bot/ and given its active history, I assumed this repository is the one where the list of CLA approved contributors are maintained and Conda was using the [cla-bot GitHub app](https://github.com/apps/cla-bot). I then realized there is a dedicate anaconda-issue-bot - https://github.com/conda/conda/pull/10627#issuecomment-824042878, from [CONTRIBUTING.md](https://github.com/conda/conda/blob/master/CONTRIBUTING.md#conda-contributor-license-agreement) that there is also a separate [.cla-signers](https://github.com/conda/conda/blob/master/.cla-signers) file and a potentially related https://github.com/conda/conda-bot-service repo.

So I was wondering which file/repository do you consider as the ground truth for the CLA records and whether your automation/notification strategy could be easily re-usable ?

/cc @joshmoore @jburel

**Comment by kenodegard** [comment]
Better late than never...

As of today the SSOT for our CLAs is .clabot in this repo, our anaconda-issue-bot is currently configured using https://github.com/conda/conda-bots.

Yes this setup is easily re-usable whether choosing to use existing tools (like cla-bot) or designing your own custom bot.
